- name: update-ca-certificates
  become: yes
  command: update-ca-certificates

- name: Move cert to all service VMs
  command: ansible services -b -u ubuntu -m copy -a "src={{ ansible_user_dir }}/keystone_juju_ca_cert.crt dest=/usr/local/share/ca-certificates/keystone_juju_ca_cert.crt owner=root group=root mode=0644"

- name: update-ca-certificates in service VMs
  command: ansible services -b -u ubuntu -m command -a "update-ca-certificates"
