---
# xos-compute-setup/tasks/main.yml
#
# Tell XOS that a new compute node has been added

- name: Create nodes/vtn TOSCA config
  template:
    src: "{{ item }}.j2"
    dest: "{{ service_profile_repo_dest }}/{{ xos_configuration }}/{{ item }}"
    owner: "{{ ansible_user_id }}"
    mode: 0644
  with_items:
    - vtn.yaml
    - nodes.yaml

- name: Rebuild VTN configuration with new nodes block
  make:
    chdir: "{{ service_profile_repo_dest }}/{{ xos_configuration }}"
    target: vtn

