---
# automation-integration/tasks/main.yml

- name: Template do-enlist-compute-node script to /etc/maas/ansible/do-enlist-compute-node
  become: yes
  template:
    src=do-enlist-compute-node.j2
    dest=/etc/maas/ansible/do-enlist-compute-node
    owner=maas
    group=maas
    mode=0755

- name: Have MAAS do-ansible script run do-enlist-compute-node script
  become: yes
  lineinfile:
    dest=/etc/maas/ansible/do-ansible
    line='/etc/maas/ansible/do-enlist-compute-node $ID $HOSTNAME || exit $?'

