---
# Installs  new compute nodes in cord-pod XOS configuration using Juju

- name: Include vars
  hosts: all
  tasks:
  - include_vars: vars/cord_defaults.yml
  - include_vars: vars/cord.yml
  - include_vars: vars/example_keystone.yml

- name: Configure compute hosts to use DNS server
  hosts: all
  become: yes
  roles:
    - { role: dns-configure, when: on_cloudlab }

- name: Prep systems
  hosts: compute
  become: yes
  roles:
    - common-prep
    - { role: cloudlab-prep, when: on_cloudlab }

- name: Configure head node (for sshkey)
  hosts: head
  roles:
    - { role: head-prep, become: yes }

- name: Configure compute nodes
  hosts: compute
  become: yes
  roles:
    - compute-prep

- name: Deploy compute nodes
  hosts: head
  roles:
    - juju-compute-setup
    - xos-compute-setup

