---
# Installs the single node cord-pod XOS configuration, using Juju to provision
# the OpenStack installation inside of VM's on the head node.
#
# This is used by `scripts/single-node-pod.sh` for E2E testing.

- name: Include vars
  hosts: head
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - vars/cord_single_defaults.yml
        - vars/cord.yml
        - vars/example_keystone.yml

- name: Check Prerequisites
  hosts: head
  roles:
    - prereqs-common

- name: DNS Server and apt-cacher-ng Setup
  hosts: head
  become: yes
  roles:
    - dns-nsd
    - dns-unbound
    - apt-cacher-ng

- name: Configure all hosts to use DNS server
  hosts: head
  become: yes
  roles:
    - dns-configure

- name: Prep systems
  hosts: head
  become: yes
  roles:
    - common-prep
    - { role: cloudlab-prep, when: on_cloudlab }

- name: Configure head node, create VM's
  hosts: head
  roles:
    - { role: head-prep, become: yes }
    - { role: config-virt, become: yes }
    - create-vms

- name: Set up VM's, juju, simulate fabric
  hosts: head
  roles:
    - xos-vm-install
    - onos-vm-install
    - juju-setup
    - simulate-fabric
    - { role: test-client-install, when: test_client_install }
    - docker-compose
    - onos-load-apps
    - xos-start
