---
# Deploys OpenStack in LXD containers on the CORD head node

- name: Include vars
  hosts: all
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - vars/cord_defaults.yml
        - vars/cord.yml
        - vars/example_keystone.yml

- name: Configure head node, create containers
  hosts: head
  roles:
    - { role: head-prep, become: yes }
    - create-lxd

- name: Start OpenStack install
  hosts: head
  roles:
    - juju-setup

# Put plays here that will execute in parallel to
# the OpenStack installation

- name: Finish OpenStack install
  hosts: head
  roles:
    - juju-finish
