---
- name: Install software
  apt:
    name={{ item }}
    update_cache=yes
    cache_valid_time=3600
  become: yes
  register: result
  until: result | success
  retries: 15
  delay: 60
  with_items:
   - lxc
   - lxc-dev
   - python-dev

- name: Install PIP packages
  pip:
    name={{ item }}
  become: yes
  register: result
  until: result | success
  retries: 15
  delay: 60
  with_items:
   - lxc-python2
