hosts: [
  { host_ip: "10.100.198.200", host_name: "platdev"},
]

use_latest_for:
  - debian-keyring
  - debian-archive-keyring
  - rng-tools
  - python-netaddr

obsolete_services:
  - puppet
  - chef-client
