---
# onos-vm-install/tasks/main.yml
#
# Install ONOS on a sub vm by calling ansible

- name: Create templated ONOS files
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/{{ item }}"
  with_items:
    - onos-setup-vars.yml
    - Dockerfile.xos-onos
    - onos-service

- name: Copy over ONOS playbook and other files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/{{ item }}"
  with_items:
    - onos-setup-playbook.yml
    - onos-docker-compose.yml
    - fabric-docker-compose.yml

- name: Run the ONOS ansible playbook
  command: ansible-playbook {{ ansible_user_dir }}/onos-setup-playbook.yml
  async: 1800
  poll: 0
  register: onos_setup_playbook

