---
# xos-start/tasks/main.yml

- name: Build XOS containers
  command: ansible xos-1 -u ubuntu -m shell \
    -a "bash -c \"set -o pipefail; cd {{ service_profile_repo_dest }}/{{ xos_configuration }}; make local_containers |& tee xos-build.out\""
  tags:
    - skip_ansible_lint

- name: Onboard services and start XOS
  command: ansible xos-1 -u ubuntu -m shell \
    -a "bash -c \"set -o pipefail; cd {{ service_profile_repo_dest }}/{{ xos_configuration }}; make xos |& tee xos-onboard.out\""
  tags:
    - skip_ansible_lint

- name: Pause to let XOS initialize
  pause: seconds=120

- name: Initial VTN configuration
  command: ansible xos-1 -u ubuntu -m shell \
    -a "cd {{ service_profile_repo_dest }}/{{ xos_configuration }}; make vtn"
  tags:
    - skip_ansible_lint

- name: Initial fabric configuration
  command: ansible xos-1 -u ubuntu -m shell \
    -a "cd {{ service_profile_repo_dest }}/{{ xos_configuration }}; make fabric"
  tags:
    - skip_ansible_lint

- name: Pause to let ONOS initialize
  pause: seconds=20
  tags:
    - skip_ansible_lint

- name: Configure CORD services
  command: ansible xos-1 -u ubuntu -m shell \
    -a "cd {{ service_profile_repo_dest }}/{{ xos_configuration }}; make cord"
  tags:
    - skip_ansible_lint

