# Deployment configuration for a single-node physical hardware POD
---
seedServer:

  # Put the IP of your target server here
  ip: '1.2.3.4'

  # User name and password used by Ansible to connect to the target server for remote
  # provisioning.   You can also run ssh-agent to allow for password-less SSH login.
  user: 'myuser'
  password: 'cord_test'

  # Uncomment if the target server is a CloudLab machine
  #extraVars:
  #  - 'on_cloudlab=True'
