# ONOS with XOS features for docker-compose
version: '2'

services:

   xos-onos:
      image: docker-registry:5000/onosproject/onos:candidate
      ports:
       - "6653:6653"
       - "8101:8101"
       - "8181:8181"
       - "9876:9876"

