---
- hosts: nova-compute-1
  remote_user: ubuntu
  become: yes

  tasks:
    - name: Include configuration vars
      include_vars: simulate-fabric-vars.yml

    - name: Install prerequisites
      apt:
        name={{ item }}
        update_cache=yes
        cache_valid_time=3600
      become: yes
      with_items:
       - bridge-utils

    - name: Create bridges
      when: "ansible_{{ item.name }} is not defined"
      command: brctl addbr "{{ item.name }}"
      with_items: "{{ simfabric_bridges }}"

