---
# juju configuration file for CORD deployments

ceilometer:
  openstack-origin: cloud:trusty-kilo

glance:
  ha-mcastport: 5402
  openstack-origin: cloud:trusty-kilo

keystone:
  ha-mcastport: 5403
  https-service-endpoints: False
  openstack-origin: cloud:trusty-kilo
  use-https: no

mysql:
   max-connections: 20000

neutron-api:
  neutron-plugin: onosvtn
  onos-vtn-ip: onos-cord
  neutron-security-groups: true
  openstack-origin: cloud:trusty-kilo
  overlay-network-type: vxlan

nova-cloud-controller:
  config-flags: "force_config_drive=always"
  console-access-protocol: novnc
  network-manager: Neutron
  openstack-origin: cloud:trusty-kilo

nova-compute:
  config-flags: firewall_driver=nova.virt.firewall.NoopFirewallDriver
  disable-neutron-security-groups: True
  openstack-origin: cloud:trusty-kilo

openstack-dashboard:
  openstack-origin: cloud:trusty-kilo

rabbitmq-server:
  ssl: 'off'

