---
# roles/dns-configure/tasks.yml

- name: Configure resolv.conf to use nameservers
  template:
    src="resolv.conf.j2"
    dest="/etc/resolv.conf"
    mode=0644 owner=root group=root

- name: Check that VM's can be found in DNS
  shell: "dig +short {{ item.name }}.{{ site_suffix }} | grep {{ item.ipv4_last_octet }}"
  with_items: "{{ head_vm_list }}"
  tags:
   - skip_ansible_lint # purely a way to pass/fail config done so far. Ansible needs a "dns_query" module

